services:
  postgres:
    image: postgres:14.14-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: wallpaper
      POSTGRES_USER: postgres
    volumes:
      - ./back/.postgres:/var/lib/postgres/data
    ports:
      - 6000:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5000:80
    restart: always

  redis:
    image: redis:7.2.6
    container_name: redis
    command: bash -c "redis-server"
    ports:
      - 6379:6379
    restart: always

  celery:
    build: ./back/celery_task/
    container_name: celery
    command: bash -c "celery -A celery_task.config:celery worker --loglevel=INFO --pool=solo"
    environment:
      CELERY_HOST: redis
    depends_on:
      - redis
    restart: always

  flower:
    image: mher/flower:2.0
    container_name: flower
    depends_on:
      - celery
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    ports:
      - 5555:5555
    restart: always

  back:
    build: ./back/
    container_name: back
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host=0.0.0.0 --port=80"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: redis
      CELERY_HOST: redis
    depends_on:
      - postgres
      - redis
      - celery
    volumes:
      - ./back:/back
    ports:
      - 8000:80
    restart: always

  front:
    build: ./front/
    container_name: front
    volumes:
      - ./front:/front
    depends_on:
      - back
    ports:
      - 80:5173
    restart: always

volumes:
  .postgres:
    driver: local
  back:
    driver: local
  front:
    driver: local
