version: "v2.29.7-desktop.1"

services:
  postgres_container:
    image: postgres:14.13
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: wallpaper
      POSTGRES_USER: postgres
    volumes:
      - ./back/.postgres:/var/lib/postgres/data
    ports:
      - 6000:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8.12
    depends_on:
      - postgres_container 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5000:80
    restart: always

  back:
    build: ./back/
    environment:
      DB_HOST: postgres_container
    depends_on:
      - postgres_container
    volumes:
      - ./back:/.log
    ports:
      - 8000:80
    restart: always

  front:
    build: ./front/
    container_name: front
    depends_on:
      - back
    ports:
      - 80:5173
    restart: always

volumes:
  .postgres:
  