from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "588e3f9243ff"
down_revision: Union[str, None] = "4ed8c4893cbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "img_table", sa.Column("img_tag", sa.String(), nullable=True)
    )
    op.add_column(
        "img_table", sa.Column("is_public", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("img_table", "is_public")
    op.drop_column("img_table", "img_tag")
    # ### end Alembic commands ###
