name: testing app
on: push

env:
  MODE: ${{ secrets.MODE }}
  DB_USER_TEST: ${{ secrets.DB_USER_TEST }}
  DB_PASS_TEST: ${{ secrets.DB_PASS_TEST }}
  DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
  DB_PORT_TEST: ${{ secrets.DB_PORT_TEST }}
  DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}

  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}

  API_KEY: ${{ secrets.API_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

  PASSWORD: ${{ secrets.PASSWORD }}
  ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}

  REDIS_HOST: redis
  REDIS_PORT: 6379


jobs:
  test:
    runs-on: ubuntu-24.04
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "6379:6379"

    steps:
      - uses: ikalnytskyi/action-setup-postgres@v6
        with:
          username: ${{ secrets.DB_USER_TEST }}
          password: ${{ secrets.DB_PASS_TEST }}
          database: ${{ secrets.DB_NAME_TEST }}
          port: ${{ secrets.DB_PORT }}
          postgres-version: "14"
          ssl: "on"
      - uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install poetry
        uses: snok/install-poetry@v1

      - name: install dependency
        run: |
          cd back
          poetry config virtualenvs.in-project true
          poetry install

      - name: create log dir
        run: mkdir .log

      - name: create token
        run: |
          cd back/src/app/auth/token
          openssl genrsa -out jwt-private.pem 2048
          openssl rsa -in jwt-private.pem -outform PEM -pubout -out jwt-public.pem 
          

      - name: run auth_pos test
        run: |
          cd back
          source ./.venv/bin/activate
          pytest tests/test_auth.py
          pytest tests/test_img/test_img.py
