name: test backend app
on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install poetry
        uses: snok/install-poetry@v1

      - name: install dependency
        run: |
          cd back
          poetry install

      - name: run auth_pos test
        run: |
          pip list
          pytest -vv -s tests/test_auth.py::TestAuthPos
