name: test backend app
on: push

env:
  MODE: ${{ secrets.MODE }}
  DB_USER_TEST: ${{ secrets.DB_USER_TEST }}
  DB_PASS_TEST: ${{ secrets.DB_PASS_TEST }}
  DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
  DB_PORT_TEST: ${{ secrets.DB_PORT_TEST }}
  DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}

  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}


jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install poetry
        uses: snok/install-poetry@v1

      - name: install dependency
        run: |
          cd back
          poetry config virtualenvs.in-project true
          poetry install

      - name: create log dir
        run: mkdir .log

      - name: run auth_pos test
        run: |
          cd back
          source ./.venv/bin/activate
          pytest -vv -s tests/test_auth.py::TestAuthPos
