name: test backend app
on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: install python
        uses: actions/checkout@v4
        with:
          python-version: 3.12

      - name: install poetry
        run: snok/install-poetry@v1

      - name: install dependency
        run: |
          cd back
          poetry install

      
